### ISSUE TITLE
Can't detect items in main and off hands

### ISSUE THREAD

**Issue by pisekpiskovec** [Spectrall368/Generator-1.16.5#6]
Using ver. 1.1.1

Procedure blocks 'Item in main-hand of ...` or 'Item in off-hand of ...` are always false when used in 'if' block

**Comment by Spectrall368** [comment]
Can you send me a picture of the procedure block you created?

**Comment by pisekpiskovec** [comment]
Ok sorry for the late reply. Here's what I basically did:
![issue_0](https://github.com/Spectrall368/Generator-1.16.5/assets/77384152/10da8058-8fae-45f3-8ace-da2d3796889b)
![issue_1](https://github.com/Spectrall368/Generator-1.16.5/assets/77384152/92db8d85-75f9-43e5-9e05-fa66f4e48e1b)

**Comment by Spectrall368** [comment]
I think it's a MCreator problem with older generators/versions. Since I haven't touched any of the code that you used in that procedure, because in 2022.3 it doesn't happen. MCreator version 2023.1 is unstable with generator 1.16.5 as there have been some modifications to MCreator (for example with biomes) that do not make the generator work properly and the version of Java using MCreator also affects this as Java 17 was put in 2023.1. I recommend you go back to 2022.3 if you want to use 1.16.5 with this tutorial: https://mcreator.net/forum/71635/change-mcreator-workspace-version
